export const projects = [
    {
        id: 1,
        title: "Generative Contemplations",
        subtitle: null,
        group: "experiment",
        category_1: "art",
        tags: ["web", "real-time software", "generative"],
        thumbnail: "/reflection.png",
        url: "/projects/generative-contemplations/index.html",
        scope: ["p5.js", "RNBO", "Web Audio API", "JavaScript"],
        date: "September 2024",
        credits: null,
        contributions: [],
    },
    {
        id: 2,
        title: "v.4MP",
        subtitle: "A Machine Learning Approach to Creating Dynamic Visual Music Systems",
        group: "project",
        category_1: "design",
        tags: ["software"],
        thumbnail: "/reflection.png",
        url: null,
        scope: ["UX Design", "UI Design", "Software Engineering"],
        date: "April 2024",
        credits: null,
        contributions: [],
    },
    {
        id: 3,
        title: "v.4MP",
        subtitle: "A Machine Learning Approach to Creating Dynamic Visual Music Systems",
        group: "project",
        category_1: "design",
        tags: ["software"],
        thumbnail: "/reflection.png",
        url: null,
        scope: ["UX Design", "UI Design", "Software Engineering"],
        date: "April 2024",
        credits: null,
        contributions: [],
    },
    {
        id: 4,
        title: "v.4MP",
        subtitle: "A Machine Learning Approach to Creating Dynamic Visual Music Systems",
        group: "project",
        category_1: "design",
        tags: ["software"],
        thumbnail: "/reflection.png",
        url: null,
        scope: ["UX Design", "UI Design", "Software Engineering"],
        date: "April 2024",
        credits: null,
        contributions: [],
    }
  ];
  