export const projects = [
    {
        id: 1,
        title: "Generative Contemplations",
        subtitle: null,
        group: "experiment",
        category_1: "art",
        tags: ["web", "real-time software", "generative"],
        thumbnail: "/reflection.png",
        url: "/projects/generative-contemplations/index.html",
        scope: ["p5.js", "RNBO", "Web Audio API", "JavaScript"],
        date: "September 2024",
        credits: null,
        contributions: [],
    },
    {
        id: 2,
        title: "v.4MP",
        subtitle: "A Machine Learning Approach to Creating Dynamic Visual Music Systems",
        group: "project",
        category_1: "design",
        tags: ["software"],
        thumbnail: "/v.4mp_cardImg.png",
        url: null,
        scope: ["UX Design", "UI Design", "Software Engineering"],
        date: "April 2024",
        credits: null,
        contributions: [],
    },
    {
        id: 3,
        title: "Accessible Safari",
        subtitle: "A Sonified Safari Experience for the Vision-Impaired through Real-Time Object Detection and Scene Description",
        group: "project",
        category_1: "design",
        tags: ["software"],
        thumbnail: "/reflection.png",
        url: null,
        scope: ["UX Design", "UI Design", "Software Engineering"],
        date: "December 2024",
        credits: ["Gururaj Deshpande", "Rochan Madhusudhan", "Shaam Bala"],
        contributions: ["Research", "Design", "Sonification"],
    },
    {
        id: 4,
        title: "Memory Mosaic",
        subtitle: "Impressions of past, present, asnd future guests are curated into a haunting art exhibition within a hotel lobby.",
        group: "project",
        category_1: "art",
        tags: ["Interactive Installation", "Real-time Software"],
        thumbnail: "/reflection.png",
        url: null,
        scope: ["UX Design", "UI Design", "Software Engineering"],
        date: "May 2024",
        credits: null,
        contributions: [],
    }
  ];
  